alnhdgrlla/Lets-gogh

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20190813090059_devise_create_users.rb
db/migrate/20190813091658_add_username_to_users.rb
db/schema.rb
test/models/user_test.rb

@alnhdgrlla Please review the user model
Generated user model with Devise gem, will need to bundle install upon pulling the master. Also please run db:migrate, username column was added to users table.

Generated user model

---

config/routes.rb

@alnhdgrlla Please review added routes
Added resources for bookings (index, show, new, create) and supplies (everything except delete). No need for db:migrate or bundle install.

Added initial routes for bookings and supplies (can update as needed)

---

app/models/booking.rb
app/models/supply.rb
app/models/user.rb
db/migrate/20190813102707_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

Created booking model, migration files pertaining to it

Generate bookings

---

Gemfile
Gemfile.lock
db/seeds.rb

@alnhdgrlla Please review seeds file
- Seeds file will generate 10 dummy users and 10 dummy supplies
- Used Faker gem, so please bundle install first
- Remember to rails db:seed!

Created seeds for users and supplies

---

app/controllers/supplies_controller.rb
test/controllers/supplies_controller_test.rb

@alnhdgrlla Please review supplies controller
- Added supplies controller with index, show, new, create, edit, and update methods
- Using strong params for create and update
- Please create views/supplies/... as appropriate

Generated supplies controller

---

app/controllers/bookings_controller.rb
app/controllers/supplies_controller.rb
test/controllers/bookings_controller_test.rb

Created bookings controller, though we'll probably have to think a little bit more about the controller methods once we figure out the routes

created bookings controller

---

db/seeds.rb

- Seeds.rb updated to only destroy_all if environment is development
- Updated Supply seeds to more appropriately assign a user
- Added Booking seeds to generate 10 random bookings based on supplied Users and Supplies
- Please run bundle install (for the Faker gem) and rails db:seed to generate the new seeds

Updated seeds file to include seeds for bookings

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/supplies_controller.rb
app/policies/application_policy.rb
app/policies/supply_policy.rb
test/policies/supply_policy_test.rb

- "pundit" in gemfile
- created policies folder
- changed controller accordingly

Added Pundit to "supplies"

---

app/controllers/supplies_controller.rb

This is the one Jacque commented on a little while ago

Fixed index method for supply controller

---

app/controllers/supplies_controller.rb

- Update method for supplies controller was redirecting to "flat_path" (doesn't exit)
- Changed path to supply_path so it should redirect properly now

Fixed update method for supplies controller

---

app/views/supplies/new.html.erb

- Added views/supplies/new.html.erb containing a simple form to allow a user to add a new supply to rent

Added simple form for adding supply

---

app/controllers/supplies_controller.rb

I put the authorize_supply method before the instance variables were initialized so of course they weren't working.  so I fixed that

fixed commit controller

---

app/controllers/bookings_controller.rb
app/policies/booking_policy.rb
test/policies/booking_policy_test.rb

Created booking pundit feature. 
- booking policy file
- booking controller (edited)

created booking pundit feature

---

app/controllers/supplies_controller.rb

- Added current_user to Supplies controller create method to fix issue where it was "silently" rejecting new supply

Added user to create method to fix issue

---

db/migrate/20190814071102_add_photo_to_supply.rb
db/schema.rb

title speaks for itself i think

added photo column to supply table

---

app/views/supplies/edit.html.erb

- Created edit.html.erb simple form for update method of Supplies controller

Added update view for supply

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_footer.scss
app/assets/stylesheets/pages/_index.scss
app/views/shared/_navbar.html.erb

1) turned icon into home button
2) moved message into dropdown

nav bar styling

---

app/controllers/supplies_controller.rb

Added :photo to strong params of supply, so that photo can be added via form

Added photo to strong params of supply

---

app/views/shared/_navbar.html.erb

1) added search bar in nav bar
2) deleted Home button from nav bar

added search bar/delete home button

---

app/views/supplies/show.html.erb

- Added if statement to check the policy for edit and display edit link for users who own the supply

Added pundit validation for edit view of Supply

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/supplies_controller.rb
app/uploaders/photo_uploader.rb

- Added dotenv for cloudinary
- set up cloudinary environment and carrierwave
To do next: 
- include photos in seed
- display pics in view pages

Set up cloudinary

---

app/controllers/supplies_controller.rb
app/models/supply.rb
app/views/supplies/new.html.erb

fixed error in controller and model, added section to add photo in new supply form.  up next seeds!

Cloudinary works!

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

placed the footer to the bottom of the screen
but not to the bottom of the page

footer fixed half way

---

app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
app/views/bookings/new.html.erb
config/routes.rb

- Added index view for bookings, accessible through supplies/:supply_id/bookings (no button yet)
- Added new view for bookings, accessible through supplies/:supply_id/bookings/new (no button yet)
- Nested routes in router so that bookings have access to supply id
- Updated bookings controller to include user and supply for functionality

Added views for index and new, added start to functionality

---

app/views/supplies/edit.html.erb
app/views/supplies/new.html.erb

added some instruction for users to fill out the forms(new, edit)

added hints for forms

---

app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
config/routes.rb

- Moved route for bookings index outside of nesting with supply
- Removed dead link from booking index view
- Updated Bookings controller to remove dependency on supply for index

Added route for booking index

---

app/controllers/bookings_controller.rb

- Added supply to create method in bookings controller
- Rerouted the redirect to bookings page upon creation of booking

Rerouted booking creation to fix missing template issue

---

app/assets/stylesheets/pages/_home.scss
app/views/supplies/edit.html.erb
app/views/supplies/new.html.erb

1) added description form to new and edit page
2) footer is no longer hiding contents at the bottom

Adding description to forms and fixed footer

---

app/assets/stylesheets/bookings/_edit.scss
app/views/supplies/edit.html.erb
app/views/supplies/new.html.erb

waring to warning

---

app/assets/stylesheets/supplies/_edit.scss
app/assets/stylesheets/supplies/_new.scss
app/views/supplies/edit.html.erb
app/views/supplies/new.html.erb

fixing styling on buttons in new and edit page

styling of buttons

---

app/assets/stylesheets/pages/_home.scss
app/views/bookings/index.html.erb
app/views/shared/_navbar.html.erb
app/views/supplies/index.html.erb
app/views/supplies/show.html.erb

Show card edits

---

.gitignore
app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/views/bookings/_new.html.erb
package.json
yarn.lock

- Added plugin Flatpickr & associated javascript files
- Booking a supply should now show a dropdown for the start and end dates
- Please run yarn install once branch is merged!

Implemented flatpickr for supply booking form

---

Gemfile
Gemfile.lock
app/controllers/supplies_controller.rb
app/models/supply.rb
app/views/shared/_navbar.html.erb

- Added PgSearch for supplies
- Can enter search terms to search through titles, descriptions, and categories
- Please bundle install and restart server once merged (new gem needed)

Search title, category, or description through the navbar

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/views/bookings/index.html.erb

Booking index

---

Gemfile
Gemfile.lock
app/controllers/pages_controller.rb
app/controllers/supplies_controller.rb
app/models/supply.rb
app/views/pages/home.html.erb
app/views/supplies/edit.html.erb
app/views/supplies/new.html.erb
db/migrate/20190816044435_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
db/migrate/20190816044436_add_missing_unique_indices.acts_as_taggable_on_engine.rb
db/migrate/20190816044437_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
db/migrate/20190816044438_add_missing_taggable_index.acts_as_taggable_on_engine.rb
db/migrate/20190816044439_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
db/migrate/20190816044440_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
db/schema.rb

- User can add new tags upon creating new Supply
- User can add new tags when editing an existing Supply
- User can click on tags to go to all products containing tag
- Please bundle install and db:migrate, then restart server to get it functional

Tagging system

---

app/assets/stylesheets/components/_navbar.scss
app/views/supplies/edit.html.erb
app/views/supplies/new.html.erb

removed a code from navbar scss component to show the top missing part

Adding form

---

app/views/supplies/edit.html.erb

- removed all hints from edit page form

removing hints from supply edit page

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/supplies/_supply-container.scss
app/views/pages/home.html.erb
app/views/supplies/edit.html.erb

added a tag and styling in index page cards

tag styling

---

app/assets/stylesheets/components/_category-box.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/supplies/_supply-container.scss
app/views/pages/home.html.erb

the category checkboxes jacque made are in a horizontal ugly box, will fix later

Category styles

---

app/controllers/reviews_controller.rb
app/models/review.rb
app/models/supply.rb
app/models/user.rb
config/routes.rb
db/migrate/20190817032614_create_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb

- Added model for Review, dependent on User and Supply
- Added basic controller for it
- Expectation to add AJAX to it

Add review model and controller

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_tag.scss
app/views/pages/home.html.erb
app/views/supplies/new.html.erb
config/locales/simple_form.en.yml

1) removing * from the simple forms
2) removing username from index cards

small changes

---

db/seeds.rb

- Adds test user, test supplier, and some test supplies (hard-coded)
- Adds some randomly generated users
- Supplies include images & locations
- Each user should have some reviews as well (not super smart though)
- Please no more sir

Updated seeds to include reviews, locations, and photos

---

db/seeds.rb

- Random tags are added to randomly generated supplies now
- Specific tags are added to manually generated supplies

Added tags to seed

---

app/views/supplies/show.html.erb

- smol issue
- supply.name nai, supply.title desu

Fixed supply.name to supply.title
